name: Run tests (vitest)

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        description: 'The version of pnpm to use. Optional if packageManager is specified in package.json'
        type: string
        required: false
        default: ''
      PREPARE:
        description: "A script to run before the actual tests are to be executed."
        type: string
        required: false
      TEST_COMMAND:
        description: "Command to run vitest tests."
        type: string
        required: false
        default: "test:vitest"

jobs:
  run_tests_vitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Prepare
      if: ${{ inputs.PREPARE }}
      run: ${{ inputs.PREPARE }}

    - name: Run tests (vitest)
      run: pnpm run ${{ inputs.TEST_COMMAND }}
